nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.5.1.cjs

packageExtensions:
  '@swc-node/register@1.9.1':
     dependencies:
       '@swc/types': 0.1.6



